### ISSUE TITLE
Google Translate conflict

### ISSUE THREAD

**Issue by cherry83** [Frug/AJAX-Chat#154]
When on the page is added Google translator, error message is displayed "<b>TypeError: this.target.create is not a function</b>" and no sounds.

Script stop on FABridge.js: 
<i>
//create a new AS Object
create: function(className)
{
return this.deserialize(<b>this.target</b>.create(className));
}, 
</i>
<b>this.target</b> is <b>object#fI0htmrc695</b> - google translator object

How can fix that?

**Comment by Frug** [comment]
This doesn't appear to be a problem through chrome. 
Since it now supports html5, FABridge shouldn't even be necessary. Set sound to html5 and you can even remove fabridge.js
