### ISSUE TITLE
Illegal use of $_COOKIE

### ISSUE THREAD

**Issue by rankun203** [Frug/AJAX-Chat#182]
General Error
------
Illegal use of $_COOKIE. You must use the request class or request_var() to access input data. Found in /home/rankun203/html/colnect/phpbb/chat/lib/class/CustomAJAXChat.php on line 182. This error message was generated by deactivated_super_global.

After I install Ajax-chat beside my phpBB3.1.1 board, then request index.php found this error.

**Comment by Frug** [comment]
This was fixed in PR #230 and in the phpBB3.1 branch
