### ISSUE TITLE
Error during installation on phpBB3-3.1.x (AJAX-Chat-0.8.7\0.8.8)

### ISSUE THREAD

**Issue by s-s-s** [Frug/AJAX-Chat#183]
Hello
When I run the chat or the new installation (install.php) , I receive an error:
Error-Report: No database selected Error-Code: 1046

On phpBB3-3.0.12 AJAX-Chat-0.8.7\0.8.8 work fine.
Thank you.

**Comment by Frug** [comment]
@csch0 If you want to make a pull request with fixes, that's always welcome. As I understand it you're right, the hooks system introduced should negate the need to alter functions.php and possibly even the templates.

**Comment by Frug** [comment]
This is patched in the [phpbb3.1 branch](/Frug/AJAX-Chat/tree/phpbb3.1/)
The PR with changes is here Frug/AJAX-Chat#230
Or you can download the whole zip from here https://github.com/Frug/AJAX-Chat/archive/phpbb3.1.zip
Be sure to clear your browser cache or do a hard refresh if you are coming from an older version.
