### ISSUE TITLE
Wordpress :: avatars

### ISSUE THREAD

**Issue by AdamiPL** [Frug/AJAX-Chat#187]
Hi,
I'm was integrated AjaxChat with wordpress, everything works fine, but i wanna to display avatars, how to do this??

**Comment by Yushe** [comment]
You can't you would have to implement this feature into the code yourself.

**Comment by Wedmer** [comment]
You can add avatars in html template.

**Comment by Frug** [comment]
Wedmer is correct, the way to go about this is by editing the template and somehow use the user id to figure out the avatar URL. 
Please use the google group for questions.
