### ISSUE TITLE
Update for phpBB 3.1

### ISSUE THREAD

**Issue by scootergrisen** [Frug/AJAX-Chat#191]
Seems direct access to $_SERVER is not allowed in phpBB 3.1.
So could you update the code so it works with phpBB 3.1 ?

**Comment by Frug** [comment]
See issue #183

**Comment by s-s-s** [comment]
scootergrisen, try edit code in line 31 of AJAXChatLanguage.php like this:

//              if(empty($_SERVER['HTTP_ACCEPT_LANGUAGE'])) {
                if(empty($request->server['HTTP_ACCEPT_LANGUAGE'])) {

**Comment by scootergrisen** [comment]
I have deleted the chat on my website now.
But as i remember $_SERVER was used in a lot of places.

**Comment by Frug** [comment]
_SERVER was used in a ton of places, along with _REQUEST and _POST. The solution was to enable access to superglobals via $request->enable_super_globals(); in custom.php
