### ISSUE TITLE
  php 5.4 Strict Standards: Non-static method AJAXChatFileSystem::getFileContents() 

### ISSUE THREAD

**Issue by cherry83** [Frug/AJAX-Chat#192]
Hi,
With php 5.4 I get warning:

Strict Standards: Non-static method AJAXChatFileSystem::getFileContents() should not be called statically, assuming $this from incompatible context in ...../chat/lib/class/AJAXChatTemplate.php on line 37

With php 5.3 all is OK

**Comment by Frug** [comment]
This was fixed in master. You can manually fix it by reproducing the changes you see in this commit: 
https://github.com/Frug/AJAX-Chat/commit/ed891553d4f240dd19521b1656f6991f4327c591
