### ISSUE TITLE
Support multiple chat instances open at the same time

### ISSUE THREAD

**Issue by qJake** [Frug/AJAX-Chat#194]
I've integrated AJAX Chat into Drupal, and when I have multiple AJAX Chat instances open, switching channels in one invisibly sets the channel in the other (but the UI doesn't update). So, you have two instances open, one which is "correct" and the other which has a misleading channel name at the top (and in invalid history - everything from the old channel is in the history, but everything from that point on are messages from the new channel).

Please add some sort of support for multiple instances / sessions open at the same time, so that users can have multiple channels/chats open at the same time.

At the very least, in the meantime, you should patch it so that if a user tries to open a second instance, it warns them about another instance already being open.

**Comment by Frug** [comment]
The way chat was structured from the beginning makes this difficult to do in a clean way. Some people hack it up to use iframes to allow different installations to connect to the same database, but fir now this is not on the roadmap until chat gets overhauled completely. Chat stores your current room as part of your status, and this is not an array. It's just one room that you can be in at one time with one login. 
Tabbed rooms are on the long term roadmap much like PMs opening up in a window.
