### ISSUE TITLE
Chat global message

### ISSUE THREAD

**Issue by MilanRS** [Frug/AJAX-Chat#197]
It would be nice to have global message which could be added by any admin.
Every user would see this on login like:
ChatBot: Hello, user. Please read rules before asking for something.

Admins could set this like:
/addMessage Hello, user. Please read rules before asking for something.

**Comment by gWorldz** [comment]
Could try these Mods o.O

[Chat Welcome Message Mod](https://github.com/Frug/AJAX-Chat/wiki/Mod-welcome-message)
[Channel Descriptions Mod](https://github.com/Frug/AJAX-Chat/wiki/Mod-channel-descriptions)

they might require minor edits as these were written for older versions of AJAX Chat.

**Comment by Frug** [comment]
Adding messages permanently with a command like /addMessage and /removeMessage is not on the drawing board. For welcome messages, the welcome message mod gworld linked should suffice. I use it on my own install.

A global yell command like /yell would be neat, but that's a different issue.
