### ISSUE TITLE
SMF Theme Curve

### ISSUE THREAD

**Issue by wintstar** [Frug/AJAX-Chat#201]
Standard Style Curve missing

![theme_curve](https://cloud.githubusercontent.com/assets/2753863/7552976/fdfa8fc0-f6d4-11e4-8abf-ca82d202f937.PNG)

Download curve.css => http://experiri.scaricare.de/index.php?topic=3.msg27#msg27

**Comment by Frug** [comment]
Please provide this as a pr or some place I don't need to register to download.
