### ISSUE TITLE
AJAX Chat Standalone Xenforo Forum - picture images missing

### ISSUE THREAD

**Issue by wintstar** [Frug/AJAX-Chat#203]
Style XenForo
If the chat is used as standard, the image files are missing:
category-23px-light.png
form-button-white-25px.png
form-element-focus-25.png

root/css/XenForo.css
line 15, 47, 98, 108, 192, 223.
	background:* url('../../styles/default/xenforo/gradients/*')*

**Comment by Frug** [comment]
Quite right. References removed in 1e3d92b1d414fc418734ffa50748525e8c959a1a
