### ISSUE TITLE
Can't press any of the buttons/Can't send messages mainly nothing works.

### ISSUE THREAD

**Issue by Spikechrisgaming** [Frug/AJAX-Chat#204]
So i have just installed this on my website. And i login and it doesn't do anything when i send a message doesn't even say i'm online. And its not cause of my web host. It doesn't add any extra code to it.

**Comment by Spikechrisgaming** [comment]
Only error i get is a 403 on the chat.js

**Comment by fjwilson** [comment]
First of all what version of the chat did you install? If this is an
integrated version it maybe a cookie setting in lib/config.php.
Second I would check the permissions for the js folder.

**Comment by Spikechrisgaming** [comment]
What are the correct perms for the js folder?  mine are at 755 atm.

**Comment by fjwilson** [comment]
You would need at least read and execute

**Comment by Spikechrisgaming** [comment]
It has them.  and i'm on version 0.8.7 standalone.

**Comment by fjwilson** [comment]
When are you seeing this error message can you post a screenshot?

**Comment by Spikechrisgaming** [comment]
Mainly on the google chrome console logs and such http://puu.sh/ibr8f/dd95fd1c8a.png

**Comment by fjwilson** [comment]
Can you share a link?

**Comment by Spikechrisgaming** [comment]
http://jamebot-at.deathhost.tk/ and its not a edited version just some reason the page looks like that when i installed it. And it seems i have a free host but i know for a fact it doesn't add any extra code as i have used many other scripts while using it.

**Comment by fjwilson** [comment]
Definitely a permissions issue. You can get to this page
http://jamebot-at.deathhost.tk/js/custom.js but not this page
http://jamebot-at.deathhost.tk/js/chat.js.
My suggestion is to delete the file and replace it with a new copy. If that
does not work then recheck the permissions.

**Comment by Spikechrisgaming** [comment]
I don't know.. I replaced it with a new one and the chmod is 755. So now i don't really know.

**Comment by fjwilson** [comment]
I'm not a linux guru so it's a head scratcher for me. The only other
suggestion I have at this point would be to delete the chat folder and
start over again.

**Comment by Spikechrisgaming** [comment]
Might be just a web server problem

**Comment by Frug** [comment]
Please use groups for support requests.
