### ISSUE TITLE
User role wrong?

### ISSUE THREAD

**Issue by wintstar** [Frug/AJAX-Chat#205]
Is forgiven here the wrong user  id?
lib/data/users.php
https://github.com/Frug/AJAX-Chat/blob/master/chat/lib/data/users.php
$users[1]['userRole'] = AJAX_CHAT_ADMIN;
admin role must have 3 => $users[1]<= 1?

look config.php.example
https://github.com/Frug/AJAX-Chat/blob/master/chat/lib/config.php.example#L14
define('AJAX_CHAT_ADMIN', 3);

**Comment by Frug** [comment]
Please use groups for support requests.
