### ISSUE TITLE
"Access denied for user 'root'@'localhost' (using password: NO) Error-Code: 1045"

### ISSUE THREAD

**Issue by fvcody** [Frug/AJAX-Chat#210]
Having issues installing the script on PhpBB. I'm using PhpBB 3.1.5 and i'm probably doing something wrong with the databases i'm not sure.

I get the error "Error-Report: Access denied for user 'root'@'localhost' (using password: NO) Error-Code: 1045" when I visit my chat directory.

I don't really know what i'm doing wrong so any help would be much appreciated.

Thanks

**Comment by zhiephie** [comment]
Check configure in here, file name config.php. https://github.com/Frug/AJAX-Chat/blob/master/chat/lib/config.php.example#L22

**Comment by fvcody** [comment]
I checked it over and added correct a stupid mistake I made but it still shows the error for whatever reason.

**Comment by fvcody** [comment]
Edit: Now it shows this http://prntscr.com/8doya5

**Comment by zhiephie** [comment]
See this https://area51.phpbb.com/phpBB/viewtopic.php?t=45027&start=10

**Comment by wintstar** [comment]
Please look here https://github.com/Frug/AJAX-Chat/issues/191, https://github.com/Frug/AJAX-Chat/issues/183

It´s aproblem with deactivatet super global

**Comment by Frug** [comment]
This issue is caused by chat's custom.php being unable to read the database variable in phpbb3.1

It's patched and we should discuss it in usse #183
