### ISSUE TITLE
A symbolic sign after username click in file 'chat.js' - event onClick

### ISSUE THREAD

**Issue by marioene** [Frug/AJAX-Chat#211]
Can you change the onClick event on line 1271 in chat.js to put  " > " or a configurable parameter? 

Example: 

```
				+ '" onclick="ajaxChat.insertText(this.firstChild.nodeValue);">'
```
to

```
				+ '" onclick="ajaxChat.insertText(this.firstChild.nodeValue + \' > \');">'
```

Thank you!

**Comment by Frug** [comment]
This would have to be configurable or it would interfere with how people already use this feature (assuming people do). It's such a specific request I think it's better that you modify your chat to do it with a plugin than add it to base chat.
