### ISSUE TITLE
How to insert a permanent iframe with Live Indices in AjaxChat?

### ISSUE THREAD

**Issue by marioene** [Frug/AJAX-Chat#213]
How to insert a permanent iframe with Live Indices in AjaxChat?

<iframe frameborder="0" scrolling="no" height="292" width="424" allowtransparency="true" marginwidth="0" marginheight="0" src="http://indrates.investing.com/index.php?force_lang=1&pairs_ids=169;166;170;172;27;167;175;174;177;40830;179;53094;&header-text-color=%23FFFFFF&curr-name-color=%230059b0&inner-text-color=%23000000&green-text-color=%232A8215&green-background=%23B7F4C2&green-background=%23B7F4C2&red-text-color=%23DC0001&red-background=%23FFE2E2&inner-border-color=%23CBCBCB&border-color=%23cbcbcb&bg1=%23F6F6F6&bg2=%23ffffff&open=hide&last_update=hide"></iframe>

If I put this code in loggedIn.html I receive an error:
```
XML Parsing Error: not well-formed Location: http://10.5.0.15/ajaxChat/ Line Number 155, Column 190:
<iframe frameborder="0" scrolling="no" height="292" width="424" allowtranspare......
```

**Comment by Frug** [comment]
Please keep issues for bug reporting, and use google groups for support requests.
