### ISSUE TITLE
XML Parsing Error: junk after document element

### ISSUE THREAD

**Issue by GeorgeGkas** [Frug/AJAX-Chat#216]
I use 000webhost. I created my database, uploaded the project files and I get the follwoing error:

```
XML Parsing Error: junk after document element Location: http://somedomain.comli.com/ Line Number 65, Column 1:
<script type="text/javascript" src="http://stats.hosting24.com/count.php"></script>
^
```
What is the problem? I thing is something with the root node but I can't figure out it.
Can you help me?

**Comment by fjwilson** [comment]
You are using free hosting. Free hosts usally add extra code and it causes
problems.

**Comment by GeorgeGkas** [comment]
Yeap I already know that. The problem is how to solve it.

**Comment by fjwilson** [comment]
Pay for hosting.
