### ISSUE TITLE
Problem with phbpp3

### ISSUE THREAD

**Issue by jesuskaoz** [Frug/AJAX-Chat#221]
i have this structure for the chat:
http://example.org/chat
http://example.org/forum

and I edit the  lib/custom.php but this warning show when I acces the chat:

[phpBB Debug] PHP Warning: in file /hermes/bosnaweb06a/b2451/ipg.myweb/chat/lib/class/AJAXChat.php on line 2479: session_start(): open(/var/php_sessions/sess_84ecef150d4db19169aeac863c7c3b18, O_RDWR) failed: No such file or directory (2)
[phpBB Debug] PHP Warning: in file /hermes/bosnaweb06a/b2451/ipg.myweb/chat/lib/class/AJAXChat.php on line 2479: session_start(): Cannot send session cookie - headers already sent by (output started at /hermes/bosnaweb06a/b2451/ipg.myweb/chat/index.php:1)
[phpBB Debug] PHP Warning: in file /hermes/bosnaweb06a/b2451/ipg.myweb/chat/lib/class/AJAXChat.php on line 2479: session_start(): Cannot send session cache limiter - headers already sent (output started at /hermes/bosnaweb06a/b2451/ipg.myweb/chat/index.php:1)
[phpBB Debug] PHP Warning: in file /hermes/bosnaweb06a/b2451/ipg.myweb/chat/lib/class/AJAXChatHTTPHeader.php on line 36: Cannot modify header information - headers already sent by (output started at /hermes/bosnaweb06a/b2451/ipg.myweb/chat/index.php:1)
[phpBB Debug] PHP Warning: in file /hermes/bosnaweb06a/b2451/ipg.myweb/chat/lib/class/AJAXChatHTTPHeader.php on line 37: Cannot modify header information - headers already sent by (output started at /hermes/bosnaweb06a/b2451/ipg.myweb/chat/index.php:1)
[phpBB Debug] PHP Warning: in file /hermes/bosnaweb06a/b2451/ipg.myweb/chat/lib/class/AJAXChatHTTPHeader.php on line 41: Cannot modify header information - headers already sent by (output started at /hermes/bosnaweb06a/b2451/ipg.myweb/chat/index.php:1)
[phpBB Debug] PHP Warning: in file /hermes/bosnaweb06a/b2451/ipg.myweb/chat/lib/class/AJAXChatHTTPHeader.php on line 45: Cannot modify header information - headers already sent by (output started at /hermes/bosnaweb06a/b2451/ipg.myweb/chat/index.php:1)

what i do wrong? what should i do?

**Comment by fjwilson** [comment]
I think the structure of the chat is off should be
http://example.org/forum/chat. Unless http://example.org is your forum link
then it would be http://example.org/chat. These maybe related to the
version of php you are using. You can turn off warnings in index.php.

**Comment by Frug** [comment]
Please use groups for help and keep issues for bugs.
