### ISSUE TITLE
Sound Not working on Ipad/Mobile

### ISSUE THREAD

**Issue by mahtesham** [Frug/AJAX-Chat#223]
Hi,
Sound alert for a new message or login/logout is not working on Ipad and Iphone.
Can you please help ??

Thanks in advance.

**Comment by marquisite** [comment]
This is not an easy fix, as the sound relies on Flash which is missing on mobile devices like Apple iPhone/iPad, Android, Windows Phone, etc. There is some discussion for a replacement audio playback method using HTML5 (which does work on mobile devices unlike Flash) in pull request #78.

**Comment by Frug** [comment]
Closed by #78
