### ISSUE TITLE
Can't create channels

### ISSUE THREAD

**Issue by kremgaur16** [Frug/AJAX-Chat#224]
// Sample channel list:
$channels[0] = 'Lobby';
$channels[1] = 'Private';
$channels[2] = 'Channel3';
$channels[3] = 'Channel4';
?>

This won't work for some reason, what is up?

**Comment by fjwilson** [comment]
You have to update the users.php file to give access to each channel.

**Comment by Frug** [comment]
Please keep issues for issues.
