### ISSUE TITLE
clearChatList() Not working properly

### ISSUE THREAD

**Issue by mahtesham** [Frug/AJAX-Chat#231]
Hi,
I added a option 'Delete All'  to delete all the messages from the chat window,i am calling method this.clearChatList(); on click of 'Delete All'  button but it's deleting only 5 messages from chat windows and also it's slow.
Can you please tell me better option to do this.
Thanks in advance.

**Comment by fjwilson** [comment]
I thought there was already a /clear function written into the latest
version. It works on mine.

**Comment by Frug** [comment]
/clear was added in 0.8.7
https://github.com/Frug/AJAX-Chat/blob/62447049aff00e356d959b36d9eac123e6ec3038/chat/changelog.txt#L832

If you want to actually purge the database, though, you need to do that yourself.

**Comment by mahtesham** [comment]
yes i am using the latest version 0.8.7 and i am calling the same method as against command /clear i.e clearChatList() .
yes i want to delete messages from database also.

Thanks for the help.
