### ISSUE TITLE
Chat installed but not functioning

### ISSUE THREAD

**Issue by 5AF** [Frug/AJAX-Chat#232]
Chat is installed, however, no one shows up in online users and text can not be seen in the chat. 

www.fifthavenueforum.com is my website and http://www.fifthavenueforum.com/forum/chat/index.php is the link to my chat.

**Comment by patmaclondon** [comment]
Probably A SQL Problem

**Comment by 5AF** [comment]
How do I solve that issue?

**Comment by patmaclondon** [comment]
Well you can start by making it easier to register to your site, I haven't got a clue who the penguins are let alone what year they won the Stanley Cup, to the point what forum software are you using...

**Comment by patmaclondon** [comment]
Also did you give all the correct files the correct permissions?

**Comment by 5AF** [comment]
I apologize, I'm a novice when it comes to this stuff. Had one of my other admins help me create the databases for the config.php file. Where would I set those permissions?

**Comment by patmaclondon** [comment]
I need to know what sort of forum you are running and what version of ajax chat you installed... (E.G MYBB PHPBB STand Alone) If yoy want to integrate it with exicting users you need to use a different version

**Comment by patmaclondon** [comment]
Permissions are done via FTP or SSH using CHMOD, if a file can not be written to you can have these sort of problems, also if you installed the stand alone version you need to populate the chat as it will not run parallel with the forum. Can you login to the chat? or does nothing happen?

**Comment by 5AF** [comment]
PHPBB 3.1 with version 3.1.8.

I downloaded and installed this version of the chat - https://github.com/Frug/AJAX-Chat/archive/phpbb3.1.zip

**Comment by 5AF** [comment]
I can log in to the chat, but nothing happens. I ran the installer and it said it installed successfully.

**Comment by patmaclondon** [comment]
Do you see the chat?

**Comment by 5AF** [comment]
http://i.imgur.com/ktRSnQf.png

This is all I see. When you type in the chat box below and submit, nothing happens.

**Comment by patmaclondon** [comment]
So it seems your SQL database is working, what happens if you type something?

**Comment by patmaclondon** [comment]
On a Good note I've had this in the past wrecking my brain what it was again... It's been years since I used chat

**Comment by 5AF** [comment]
I can type in the chat box but nothing ever populates in the chat room.

**Comment by patmaclondon** [comment]
This is a tough one as I can't look into your configs, but it's seems to be that, e.g your config.php or SQL, I also just read that the latest version of PHPBB doesn't like Ajax Chat that much

**Comment by patmaclondon** [comment]
I can look into it a bit more tomorrow, as it's 11.30PM here now. all my contact details are on http://patmac.co.uk

**Comment by Frug** [comment]
Hello gentlemen, please use google groups for discussing support requests. This is for reporting issues.

**Comment by 5AF** [comment]
There is no support on the Google groups page. No one every posts there.
