### ISSUE TITLE
Cannot get shoutbox to work

### ISSUE THREAD

**Issue by raffamaiden** [Frug/AJAX-Chat#234]
I cannot get the shourbot to work. I'm on Windows 8, Apache 2.4, PHP 7.0.4, MySql 5.7.11 community, AJAX-Chat from master branch at 2016/04/25

I put this file inside the chat subfolder. Only a textbox shows and the copyright below it. There is no buttons, no graphics at all, even pressing enter on the text box does nothing

`<?php

define('AJAX_CHAT_PATH', realpath(dirname($_SERVER['SCRIPT_FILENAME'])).'/');
define('AJAX_CHAT_URL', realpath(dirname($_SERVER['SCRIPT_FILENAME'])).'/');

function getShoutBoxContent() {

// URL to the chat directory:
if(!defined('AJAX_CHAT_URL')) {
	define('AJAX_CHAT_URL', './chat/');
}

// Path to the chat directory:
if(!defined('AJAX_CHAT_PATH')) {
	define('AJAX_CHAT_PATH', realpath(dirname($_SERVER['SCRIPT_FILENAME']).'/chat').'/');
}

// Validate the path to the chat:
if(@is_file(AJAX_CHAT_PATH.'lib/classes.php')) {
	
	// Include Class libraries:
	require_once(AJAX_CHAT_PATH.'lib/classes.php');
	
	// Initialize the shoutbox:
	$ajaxChat = new CustomAJAXChatShoutBox();
		
	// Parse and return the shoutbox template content:
	return $ajaxChat->getShoutBoxContent();
}

else echo "classes.php not found";

return null;
}

function regularChat()
{
	// Initialize the chat:
	$ajaxChat = new CustomAJAXChat();
}

echo '
<html lang="en">

<head>
<style>
@import url("./css/shoutbox.css");
</style>

</head>

<body>
';

echo getShoutBoxContent();

echo'
</body>

</html>
';

?>`

**Comment by Frug** [comment]
For support questions use google groups: https://groups.google.com/forum/#!forum/ajax-chat
