### ISSUE TITLE
can't write PHP code inside template

### ISSUE THREAD

**Issue by jodenz** [Frug/AJAX-Chat#238]
I can't write PHP code inside template even though i change the file extension to .php instead of .html, thanks in advance.. thanks

**Comment by Frug** [comment]
templates are not meant to support raw php inside them. Write your php inside another file and add it to the template as a variable here https://github.com/Frug/AJAX-Chat/blob/master/chat/lib/class/AJAXChatTemplate.php#L62

**Comment by jodenz** [comment]
@Frug HI thank you for your quick reply, i am not really that expert in php. can you give me example on this scenario, i want to make the log.in userName view in some place of my template and i want also add location per user to the online list. 

Thanks in advance..
