### ISSUE TITLE
Blank shoutbox

### ISSUE THREAD

**Issue by Darklolimaster** [Frug/AJAX-Chat#243]
Hello guys !

I have an issue with the shoutbox on my website. It's remain blank. When I write and press enter (or send) it happens nothing.

But when I am on the "chatbox room" all messages are normally send. 

Do you know why this issue happen ?

Thank you for reading. I hope my explanation was clear enough. Feel free to ask me if you need some information.

**Comment by virtueless** [comment]
You should check your browser console to see if you're getting any JS / AJAX error.

**Comment by fjwilson** [comment]
So are you saying that when you submit a message in the shoutbox it appears
n the chat room?

**Comment by Darklolimaster** [comment]
@virtueless I got this error in my browser console : [https://s8.postimg.org/zark5jkur/Capture.png](url)
@fjwilson It doesn't, the message is not submitted at all

**Comment by Frug** [comment]
Please use google groups for support.
