### ISSUE TITLE
Old messages displayed to new guests/users

### ISSUE THREAD

**Issue by Risewater** [Frug/AJAX-Chat#245]
In the previous versions, once you log in messages made by previous users were not displayed. At the same time if you logged out and in again, messages were also wiped from the chat. However now messages still appear hours afterwards. How do I change that?

Thank you very much.

**Comment by Frug** [comment]
It's always been a config setting
https://github.com/Frug/AJAX-Chat/blob/master/chat/lib/config.php.example#L157
