### ISSUE TITLE
Feature request: Include file sending in chat

### ISSUE THREAD

**Issue by damms005** [Frug/AJAX-Chat#248]
Thanks for the wonderful project!

However, is there any provision to include file sending feature to this great chat?

For example, I may want to send screen-shots to my chat partner, etc.

Thank you

**Comment by Tymewalk** [comment]
You could send it as an `[img]`.

Or you could just host it somewhere else (GitHub Gist?) and then give them the link.

**Comment by zwiebus** [comment]
i use a script like [php-space-uploadscript](http://www.php-space.info/bilder-upload-script/) for this.
use this or find something similiar or more useful for your wishes.

change it to your own needs.

install it in the ajaxchat direction in a folder named upload.

add a new Button in  loggedIn.php :

row:  ~146

`                        <input type="button" value="File" title="title" onclick="window.open('upload/','_blanc')"/></div>` 

last but not least save the uploadfolder with htacess and htpasswd if your script don't provide userlogins .

**Comment by pigeonburger** [comment]
Got all kinds of virus warnings clicking on that link. Are there any alternatives to uploading files?

**Comment by damms005** [comment]
@pygeonburger maybe you should avoid using this package in newer projects (and probably replace its existing installations), as it appears unmaintained
