### ISSUE TITLE
Adding a field at log in to be displayed in chat 

### ISSUE THREAD

**Issue by leemer123** [Frug/AJAX-Chat#256]
How can I add a field input at sign in to be displayed in chat>?

**Comment by Jugolo** [comment]
You need to tell a little more what you need

**Comment by leemer123** [comment]
I am needing a grid square field to be added to the chat at registration that would display a Maidenhead grid locator 6 digit field beside the user's name in chat with a space in-between.  I am having a hard time wrapping my brain around everything , with info here, info there.  It would be super cool to have a calculation of distance in-between grids when clicked on the grid location section in chat, but i'm sure that is something really advanced.
