### ISSUE TITLE
no sound notification with safari

### ISSUE THREAD

**Issue by ghost** [Frug/AJAX-Chat#257]
with safari 10.1 (on macOS Sierra 10.12.4) , the notification sounds do not work with safari. No sound at all...
I checked the parameters :  volume 100%, sounds defined (sound_1,etc...), and the speaker icon ON 

For information, I just install firefox to check,  and with firefox it works well.

So the is a problem in AJAX-Chat with Safari...

**Comment by Rederix** [comment]
Safari does not support flash peripherals. Please use a different browser.
