### ISSUE TITLE
Need help with Ajax-Chat ( ERROR 404 and ERROR 503 )

### ISSUE THREAD

**Issue by BloxCord** [Frug/AJAX-Chat#264]
I got 2 errors I pulled everything inside out nothing found 
no logs I looked everywhere in Cpanel can noth find the problem
the errors are Fout: Verbindingsstatus: 404 and the 503

Thx for the ppl that willing to help me.

**Comment by patmaclondon** [comment]
It can't find the link, this has nothing to do with Cpanel in my opinion, Cpanel is for hosting, it's in your code mate, or in the database.

**Comment by fiber-hosting** [comment]
Also checked everything
nothing helps

**Comment by patmaclondon** [comment]
A 404 gets generated when not found, your SQL database, or server is causing this Cpanel is just a layer on top of your server

**Comment by patmaclondon** [comment]
Do you have by any chance a .htaccess file? that could cause the problem

**Comment by fiber-hosting** [comment]
Problem Solved Thnx for your help

**Comment by patmaclondon** [comment]
What was the problem?
