### ISSUE TITLE
Installation information missing

### ISSUE THREAD

**Issue by greencopper** [Frug/AJAX-Chat#265]
On the website it says:

> Each version of AJAX Chat comes with a readme file with instructions on how to proceed with these steps.

But the readme.md file contains absolutely nothing about installation.

During installation the following error appear:

```
Error-Report: No such file or directory Error-Code: 2002 
```

Pretty useless error message!

**Comment by Rederix** [comment]
Instructions for installation are also available on the resource's website.
https://github.com/Frug/AJAX-Chat/wiki/Installing
