### ISSUE TITLE
Function deprecation in PHP 7.2

### ISSUE THREAD

**Issue by ssoworld** [Frug/AJAX-Chat#276]
Major bug in upgrades - Some Hosting providers forcing use of 7.2 for their services.
as shown in capture of debug scripting below from 0.8.8:

> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Load.php on line 178
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Load.php on line 183
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Load.php on line 184
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Load.php on line 220
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Load.php on line 223
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Load.php on line 235
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Load.php on line 250
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Load.php on line 268
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Subs.php on line 1095
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Subs.php on line 1137
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Subs.php on line 1186
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Subs.php on line 1202
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Subs.php on line 1221
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Subs.php on line 1232
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Subs.php on line 1312
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Subs.php on line 1323
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Subs.php on line 1399
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Subs.php on line 1419
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Subs.php on line 1518
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Subs.php on line 1543
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Subs.php on line 1580
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Subs.php on line 1611
> 
> Deprecated: Function create_function() is deprecated in /homepages/13/d117650366/htdocs/aaroads.com/forum/Sources/Subs.php on line 1622
> 
> Notice: SSI.php was unable to load a session! This may cause problems with logout and other functions - please make sure SSI.php is included before *anything* else in all your scripts! in /homepages/13/d117650366/htdocs/aaroads.com/forum/SSI.php on line 171

**Comment by wintstar** [comment]
No commit have been added since 6 Jan 2017. Since then there has been no further development.

**Comment by Frug** [comment]
Sorry, I'm not sure if/when I will have the time to pick it up again. It's definitely in need of some overhauls like using composer and php 7.x. Not to mention modern javascript.

I can't see myself supporting all the forums that were supported in the past either. PhpBB is the only one I've got installed anywhere. 

That said, the deprecation warnings and notice provided in this issue aren't part of AJAX chat.

**Comment by wintstar** [comment]
@Frug, I will support you at SMF 2.0.17 and 2.1RC*.

**Comment by ssoworld** [comment]
@wintstar @Frug - just wanted to remind you guys that our host is giving us a shorter timeline for this and I can understand @Frug's statement with time allotted.  The host is charging our forum owner for use of 7.1 as they are not fully supporting it.  I've asked them to track the root cause of the deprecations.  There were other issues with single-sign on (maybe?) causing all chatters to be minimium of "mod" level. (A different issue nonetheless)

**Comment by Jugolo** [comment]
Hmm if it can help i can look on it 🤔

**Comment by ivellios1988** [comment]
Looks like with PHP 8.1 the situation got even worse. Chat isn't even loading for me.

**Comment by wintstar** [comment]
> No commit have been added since 6 Jan 2017. Since then there has been no further development.

**Comment by zwiebus** [comment]
the last version with which the chat (standalone 0.8.8) works properly is PHP 7.4.30
