### ISSUE TITLE
Broken?

### ISSUE THREAD

**Issue by g0dzcsgo** [Frug/AJAX-Chat#280]
Anytime i try to write something in the chat it says "Plugin blocked" in chrome, and then says FLASH is no longer a thing? I use it on FluxBB.

**Comment by wintstar** [comment]
Flash Player is end, is did.  No browser more support flash player.

https://www.infosecurity-magazine.com/news-features/flash-post-support/

**Comment by g0dzcsgo** [comment]
Yes but why is this GitHub still up then? And my chat was working like 1day ago?

**Comment by g0dzcsgo** [comment]
It doesn't even use flash?
