### ISSUE TITLE
Messages Clearing

### ISSUE THREAD

**Issue by bdbbrsvrwwv** [Frug/AJAX-Chat#286]
how to prevent the messages cleaning after some time?

**Comment by zwiebus** [comment]
you can define in config.php if and how long messages are stored in the database: 

// Defines if old messages are purged from the database:
$config['logsPurgeLogs'] = false;
// Max time difference in days for old messages before they are purged from the database:
$config['logsPurgeTimeDiff'] = 1;

if you mean the retrograde display of messages in the chat is also there:

// Defines if messages are shown which have been sent before the user entered the channel:
$config['requestMessagesPriorChannelEnter'] = true;
// Defines an array of channelIDs (e.g. array(0, 1)) for which the previous setting is always true (will be ignored if set to null):
$config['requestMessagesPriorChannelEnterList'] = null;
// Max time difference in hours for messages to display on each request:
$config['requestMessagesTimeDiff'] = 2;
// Max number of messages to display on each request:
$config['requestMessagesLimit'] = 15;
