### ISSUE TITLE
Demo page not working 

### ISSUE THREAD

**Issue by Methen** [Frug/AJAX-Chat#287]
https://www.softaculous.com/softaculous/demos/AJAX_Chat

tries on xp and windows 10 when you click the login button nothing happens

**Comment by Frug** [comment]
Where did you find a link to that demo page?

I remember seeing it in the past, but I'm not finding a link to it in this project now.

**Comment by Methen** [comment]
Do not remember  I was just searching ajax chat and ran across it though it belonged to this site 
  ----- Original Message -----
