### ISSUE TITLE
Sourceforge problem

### ISSUE THREAD

**Issue by Neustradamus** [Frug/AJAX-Chat#292]
Dear @Frug,

In first, I wish you a Happy New Year 2024!

I contact you because there is a problem on Sourceforge, the link in moved box is not good.
- https://sourceforge.net/projects/ajax-chat/

The problem is in default website too and here too:
- https://sourceforge.net/projects/ajax-chat/support
- https://sourceforge.net/p/ajax-chat/news/

Can you change it to https://github.com/Frug/AJAX-Chat?

Can you remove the "Code" tab too?

Thanks in advance.

**Comment by Frug** [comment]
> Dear @Frug,
> 
> In first, I wish you a Happy New Year 2024!
> 
> I contact you because there is a problem on Sourceforge, the link in moved box is not good.
> 
>     * https://sourceforge.net/projects/ajax-chat/
> 
> 
> The problem is in default website too and here too:
> 
>     * https://sourceforge.net/projects/ajax-chat/support
> 
>     * https://sourceforge.net/p/ajax-chat/news/
> 
> 
> Can you change it to https://github.com/Frug/AJAX-Chat?
> 
> Can you remove the "Code" tab too?
> 
> Thanks in advance.

Hi Neustradamus, thanks for bringing this to my attention. I'll take a look. Sourceforge is so long ago I'd forgotten about it completely.

**Comment by Frug** [comment]
I've updated the links.
